language: node_js
sudo: required
dist: trusty
node_js:
  - '5.1'
cache:
  directories:
    - bower_components
before_script:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm i -g bower firebase-tools polymer-cli
  - bower i
script:
  - ./travis-runner.sh